magic_numbers:

  # ====== For clarity =======
  # if similarity score fetched from column name(header name) is greater than threshold
  # Then we are confident that this is the right column and we do no need check other columns
  clarity_threshold: 0.75

  # final_similarity_score = (sim_score_from_col_name*clarity_normalizing_factor_for_col_name) + (sim_score_from_col_val * clarity_normalizing_factor_for_col_value)
  clarity_normalizing_factor_for_col_name: 0.5
  clarity_normalizing_factor_for_col_value: 0.5

  carat_normalizing_factor_for_col_name: 0.75
  carat_normalizing_factor_for_col_value: 0.25

  color_threshold: 0.75
  color_normalizing_factor_for_col_name: 0.5
  color_normalizing_factor_for_col_value: 0.5

  # This is used during post-processing stage
  # where we transform non-standard value to standard value.
  # There while using the string_similarity function we need this threshold parameter
  shape_similarity_transform_df_threshold: 0.7
  
  fluor_similarity_threshold: 0.8
  fluor_normalizing_factor_for_col_name: 0.5
  fluor_normalizing_factor_for_col_value: 0.5
  fluor_similarity_transform_df_threshold: 0.3

  raprate_threshold_factor: 0.8
  raprate_normalizing_factor_for_col_name: 0.5
  raprate_normalizing_factor_for_col_value: 0.5

  measurement_normalizing_factor_for_col_name: 0.4
  measurement_normalizing_factor_for_col_value: 0.6
  
  cut_similarity_threshold: 0.8
  cut_normalizing_factor_for_col_name: 0.5
  cut_normalizing_factor_for_col_value: 0.5
  cut_similarity_transform_df_threshold: 0.7

  polish_similarity_threshold: 0.8
  polish_normalizing_factor_for_col_name: 0.5
  polish_normalizing_factor_for_col_value: 0.5

  sym_similarity_threshold: 0.8
  sym_normalizing_factor_for_col_name: 0.5
  sym_normalizing_factor_for_col_value: 0.5
  
   
  table_threshold_factor: 0.8
  table_normalizing_factor_for_col_name: 0.5
  table_normalizing_factor_for_col_value: 0.5

  comments_threshold_factor: 0.8
  comments_normalizing_factor_for_col_name: 0.7
  comments_normalizing_factor_for_col_value: 0.3
  comments_similarity_threshold: 0.8

  ppc_threshold_factor: 0.8
  ppc_normalizing_factor_for_col_name: 0.5
  ppc_normalizing_factor_for_col_value: 0.5
  ppc_similarity_threshold: 0.8

  disc_threshold_factor: 0.8
  disc_normalizing_factor_for_col_name: 0.3
  disc_normalizing_factor_for_col_value: 0.7
  disc_similarity_threshold: 0.8

  amt_threshold_factor: 0.8
  amt_normalizing_factor_for_col_name: 0.5
  amt_normalizing_factor_for_col_value: 0.5
  amt_similarity_threshold: 0.8

  raptotal_threshold_factor: 0.8
  raptotal_normalizing_factor_for_col_name: 0.5
  raptotal_normalizing_factor_for_col_value: 0.5
  raptotal_similarity_threshold: 0.8