 # uncomment below lines to use CML

name: DVC-project
 
on: [push]
 
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          pyhon-version: '3.7'
      - name: Install dependencies and run all unit test
        env:
          REPO_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --use-pep517
          python unit_testing/run_all_unit_tests.py 
      
          